```yml
title: Gravitational Wave with Deep Learning Project
description: Deep Learning pipeline for analyzing LIGO gravitational-wave signals using Convolutional Neural Networks (CNNs)

markdown: kramdown
highlighter: rouge

kramdown:
  math_engine: mathjax
  input: GFM

plugins:
  - jekyll-seo-tag
```
