title: "Gravitational Wave with Deep Learning Project"
description: "Deep Learning pipeline for analyzing LIGO gravitational-wave signals using CNNs"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  math_engine: mathjax

plugins:
  - jekyll-seo-tag
